---
- name: restart php-fpm
  service:
    name: "php{{ php_version }}-fpm"
    state: restarted
  when: php_handler == 'fpm'

- name: restart apache (for mod_php)
  service:
    name: apache2
    state: restarted
  when: php_handler != 'fpm'
